src/objects/Case_Team__c.object
<CustomObject>
    <description>Used to look up the case record type and team based on the incoming email address</description>
    <fields>
        <fullName>Email_Service_Address__c</fullName>
        <description>Email Service Address used to lookup the record type</description>
        <inlineHelpText>Email Service Address used to lookup the record type</inlineHelpText>
        <label>Email Service Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>CaseTeams</relationshipLabel>
        <relationshipName>CaseTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CaseTeam</label>
    <nameField>
        <label>Case Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaseTeams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Localized_Auto_Response__c.object
<CustomObject>
    <fields>
        <fullName>CaseTeam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CaseTeam</label>
        <referenceTo>Case_Team__c</referenceTo>
        <relationshipLabel>Localized Auto Responses</relationshipLabel>
        <relationshipName>Localized_Auto_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Template_Id__c</fullName>
        <label>Email Template Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Localized Auto Responses</relationshipLabel>
        <relationshipName>Localized_Auto_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Localized Auto Response</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Localized Auto Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmailTemplateClass.cls
public with sharing class EmailTemplateClass {
	
	public static String getReplyText(string bodyText, string newLine, string originalText){
		return bodyText + newLine + newLine + Utilities.repeatString('#', 25) + ' YOUR REQUEST ' + Utilities.repeatString('#', 25) + newLine + newLine + originalText;
	}
	
	public static EmailTemplate findByLanguageOrDefault(string fromAddress, Id languageId){
		Localized_Auto_Response__c myAutoResponse;
		List<Localized_Auto_Response__c> languageAutoResponses = [SELECT Id, Email_Template_Id__c FROM Localized_Auto_Response__c WHERE Language__c = :languageId AND CaseTeam__r.Email_Service_Address__c = :fromAddress];
		if (languageAutoResponses.size() == 1) {
			myAutoResponse = languageAutoResponses[0];
		} else {
			// TODO: Get in one Query
			myAutoResponse = [SELECT Id, Email_Template_Id__c FROM Localized_Auto_Response__c WHERE CaseTeam__r.Email_Service_Address__c = :fromAddress AND Default__c = true LIMIT 1];
		}
		return [SELECT Id, Body, HtmlValue FROM EmailTemplate WHERE Id = :myAutoResponse.Email_Template_Id__c LIMIT 1];
	}

}